### ISSUE TITLE
KeyError problem

### ISSUE THREAD

**Issue by polarbear55688** [PIC4SeR/AcT#10]
Sorry to bother you, when I running this program,it show KeyError: 'openpose_legacy' . I check the file and it shows that the problem is in python3.7/site-packages/mpose/mpose.py", line 81, in set_data_config self.K = self.config['DATASET'][self.pose_extractor]['K']
I want to know how to solve it.
Thank you!

**Comment by simoneangarano** [comment]
Sorry, just change 'openpose_legacy' to 'openpose', and everything should work fine. That configuration was for an older version of the mpose package, which has recently been updated.
I hope this solves your problem!

**Comment by polarbear55688** [comment]
It's working! thank you very much
