### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by chags1313** [PIC4SeR/AcT#14]
I ran into an issue while installing requirements with numpy==1.20.3. Here is the message `Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/`.

I'm assuming that downloading visual studio would solve the issue. However, I installed the latest version of numpy (1.21.6) and it now works. Sharing this in case others run into the same problem.

**Comment by simoneangarano** [comment]
I guess this is a Windows compatibility issue. I don't have the same problem on Linux, but thanks for sharing!
