### ISSUE TITLE
Requesting for the trained best model

### ISSUE THREAD

**Issue by Yann-Ma** [PIC4SeR/AcT#5]
Hi,

Thanks for your work on real-time human action recognition. I am trying to apply a HAR application on a mobile device. 

**My question is: Could you provide the trained best model to the public?** 

If so, we don't need to train a model and we can use the best model to make inferences directly. It will provide much convenience. Thank you.

**Comment by simoneangarano** [comment]
Hi @Yann-Ma ,
I added a [link](https://drive.google.com/file/d/1NRMg3BWEDHC7aqCLp1mIUxYjuqPsQ8Ty/view?usp=sharing) to download weights in the readme!
Thanks for asking. I hope it's useful for your project!
Simone

**Comment by Yann-Ma** [comment]
> 

Thanks a lot! It's quite helpful!
