### ISSUE TITLE
Using videos with different length

### ISSUE THREAD

**Issue by lluisp1999** [PIC4SeR/AcT#7]
Hi!

I have been digging into your code and I still don't understand how you cope with videos that have a different duration for the training set. Could you give me some more information?

Thanks!

**Comment by simoneangarano** [comment]
Hi @lluisp1999,
We used fixed-size samples of 30 frames each in our work as we focused on short-time HAR. However, I'm sure our approach could also work with longer sequences. You should choose a fixed and big-enough input sequence length and zero-pad shorter samples. That is also what we did for our training dataset.
I hope this helps!
